import * as types from './BusinessTypes'

export default Subtypes = {
  [types.RETAIL]: {
    title: 'Retail Stores',
    collection: 'listings',
    singular: 'listing',
    subtypes: [
      'Dispensary',
      'Headshop',
      'Hydroponics & Indoor Gardening',
      'Garden Center',
      'General Merchandise',
      'Restaurant',
      'Social Club',
      'Other Retail',
    ],
    channels: ['Store Front', 'Delivery', 'Online'],
    amenities: [
      'Accepts Credit Card',
      'ATM',
      'Medical',
      'On-site Security',
      'Recreational',
      'Wheelchair Accessible',
    ],
  },
  [types.SERVICE]: {
    title: 'Services',
    collection: 'services',
    singular: 'service',
    subtypes: [
      'Advertising',
      'Architect',
      'Association',
      'Banking',
      'Bookkeeper',
      'Construction',
      'Consultant',
      'Cryptocurrency',
      'CPA',
      'Distributor',
      'Doctor',
      'Educator',
      'Insurance',
      'Investor',
      'Job Staffing',
      'Lawyer',
      'Lobbyist',
      'Nutraceutical',
      'Manufacturer',
      'Marketing',
      'Organization',
      'Packaging',
      'Pharmaceutical',
      'Public Relations',
      'Realtor',
      'Security',
      'Testing Lab',
      'Transporter',
      'Web Developer',
      'Other Service',
    ],
    channels: ['Store Front', 'Online'],
    amenities: ['Accepts Credit Card', 'ATM', 'On-site Security'],
  },
  [types.INFLUENCER]: {
    title: 'Influencers',
    collection: 'influencers',
    singular: 'influencer',
    subtypes: ['Artist', 'Model', 'Musician', 'Other Influencer'],
    channels: ['Store Front', 'Delivery', 'Online'],
    amenities: ['Accepts Credit Card'],
  },
  [types.BRAND]: {
    title: 'Brands',
    collection: 'brands',
    singular: 'brand',
    subtypes: [
      'Cannabis',
      'Cannabis Accessory',
      'Fertilizers & Nutrients',
      'Greenhouses & Related Products',
      'Grow Lights & Related Products',
      'Grow Products & Supplies',
      'Hydroponic Equipment & Products',
      'Magazine',
      'Merchandise',
      'Seed',
      'Other Product',
    ],
    channels: ['Store Front', 'Delivery', 'Online'],
    amenities: [
      'Accepts Credit Card',
      'ATM',
      'Medical',
      'On-site Security',
      'Recreational',
      'Wheelchair Accessible',
    ],
  },
}
